# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 02:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Account')),
                ('name', models.CharField(max_length=50)),
                ('PIB', models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9, message='PIB must be exactly 9 chars long.')])),
                ('LK', models.CharField(max_length=50)),
                ('uID', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Component')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ComponentCategory'),
        ),
    ]
