# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='componentavailable',
            options={'verbose_name': 'component availability', 'verbose_name_plural': 'component availabilites'},
        ),
        migrations.AlterModelOptions(
            name='componentcategory',
            options={'verbose_name_plural': 'component categories'},
        ),
    ]
